sudo: required
services:
  - docker

before_install:
  - docker build -t pramod002/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pramod002/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-738209103830"
  bucket_path: "docker-react"
  on:
    branch: master
    #  acess_key_id: $AWS_ACCESS_KEY
    #  secret_access_key:
    #    secure: "AWS_SECRET_KEY"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
#coment
